package com.decisionhorizon;

public enum DecisionTrigger {
    ENTER_NODE,
    TURN_START,
    DRAW_CARDS,
    RANDOM_CARD_GENERATED,
    CARD_GENERATION_OPTIONS,
    ENTROPIC_BREW_OPENED,
    REWARD_SCREEN_OPENED,
    CARD_REWARD_OPENED,
    CHEST_OPENED,
    SHOP_RESTOCKED,
    ENEMY_INTENT_CHANGED,
    NEW_ACT_MAP_VISIBLE,
    CARD_TRANSFORMED,
    RANDOM_CARD_UPGRADED,
    MUMMIFIED_HAND_ACTIVATED,
    TRUE_GRIT_RANDOM_EXHAUST,
    RANDOM_TARGET_CARD_PLAYED,
    CHAOS_PLAYED,
    WHITE_NOISE_PLAYED,
    INFERNAL_BLADE_PLAYED,
    DISTRACTION_PLAYED
}